name: CI
on:
  push:
    branches: [ public ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: public
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1.1.1
        with:
          secretId: ${{ secrets.SECRETID }}
          secretKey: ${{ secrets.SECRETKEY }}
          envId: ${{ secrets.ENVID }}
          staticSrcPath: ./
